// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8MA0L7e7oUKCxm0sahy8nOnueYG8enwU',
    appId: '1:429607965081:web:fc896bf3ea5b13ee5dc308',
    messagingSenderId: '429607965081',
    projectId: 'flutter-my-app-bbc77',
    authDomain: 'flutter-my-app-bbc77.firebaseapp.com',
    storageBucket: 'flutter-my-app-bbc77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNSXCFqMtN7t4bMh_wlVpAsiY_x7UErA4',
    appId: '1:429607965081:android:0951529e6accd9015dc308',
    messagingSenderId: '429607965081',
    projectId: 'flutter-my-app-bbc77',
    storageBucket: 'flutter-my-app-bbc77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcKR2bxuSd-DFkarA3araJ37GrCEsPykI',
    appId: '1:429607965081:ios:0d6a6fb743e6a7325dc308',
    messagingSenderId: '429607965081',
    projectId: 'flutter-my-app-bbc77',
    storageBucket: 'flutter-my-app-bbc77.appspot.com',
    iosClientId: '429607965081-ch4k3m989th08lllj2p1a6c4c5m6ajeh.apps.googleusercontent.com',
    iosBundleId: 'com.ruru.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcKR2bxuSd-DFkarA3araJ37GrCEsPykI',
    appId: '1:429607965081:ios:f499fe85a292e6805dc308',
    messagingSenderId: '429607965081',
    projectId: 'flutter-my-app-bbc77',
    storageBucket: 'flutter-my-app-bbc77.appspot.com',
    iosClientId: '429607965081-je7l09656a6e6k44fnlcdfm15ussl1ll.apps.googleusercontent.com',
    iosBundleId: 'com.ruru.firebase.RunnerTests',
  );
}
